name: greet Nirlo

on:
  push:
    branches: [ master ]

jobs:
  greet_nirlo_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Greeting Nirlo 
        uses: ./actions/
        id: hello
        with:
          who-to-greet: 'Nirlo'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"